Modules Addition & Fixing the Components logic
OmerMeshulam/AngularComponent pull request #2
Opened 2022-04-13 20:45 UTC by OmerMeshulam

2022-04-13 22:08 UTC, NoamGaash commented on src/app/app.component.html
> +  <app-container headerTitle="אירוע חדש" (closeContainer)="closeApp=true" *ngIf="!closeApp">
מה החשיבות של `closeApp`?
אני לא חושב שזה צריך להיות משתנה. אולי פונקציה.

2022-04-13 22:10 UTC, NoamGaash commented on src/app/app.component.ts
> +  hasClicked(buttonId: string){
יותר קריא פונקציה נפרדת לכל כפתור

2022-04-13 22:11 UTC, NoamGaash commented on src/app/app.component.ts
> +      }, 1500);
למה לחכות שנייה וחצי?

2022-04-13 22:12 UTC, NoamGaash commented on src/app/input/input.component.ts
> +  this.inputValueChange.emit(value);
יופי

2022-04-13 22:15 UTC, NoamGaash commented on src/app/toggle/toggle.component.html
> +    <input (change)="toggleSwitched()" class="checkbox" type="checkbox" id="toggle" [(ngModel)]="isChecked">
השם toggleSwitched מוצלח בעיני.
הרי אפשר לסמן את הצ'קבוקס גם עם עכבר אבל גם עם מקלדת (מקש רווח).
אחרים בצוות היו רושמים toggleClicked - אם אתה רואה בpull requests של אנשים אחרים טעויות מהסוג הזה זה מסוג הדברים שאתה יכול לכתוב עליהם בתגובה לPR-ים.

2022-04-13 22:17 UTC, NoamGaash requested changes
עבודה טובה, רק closeApp מפריע לי

2022-04-14 07:53 UTC, OmerMeshulam commented on src/app/app.component.html
> +  <app-container headerTitle="אירוע חדש" (closeContainer)="closeApp=true" *ngIf="!closeApp">
כאשר לוחצים על האיקס בקונטיינר נשלח Event לאב שמעדכן את closeApp בשביל לסגור את האפליקצייה.

2022-04-14 07:53 UTC, OmerMeshulam commented on src/app/app.component.ts
> +  hasClicked(buttonId: string){
אוקיי.

2022-04-14 07:55 UTC, OmerMeshulam commented on src/app/app.component.ts
> +      }, 1500);
כאשר אתה לוחץ על ביטול הוא רושם ב-Dropdown שהבחירה נמחקה ל-1.5 שניות ואז משנה את ה-Placeholder חזרה ל-"בחר תחביב". זה סתם נראה יותר טוב לדעתי.

2022-04-14 07:57 UTC, OmerMeshulam commented on src/app/toggle/toggle.component.html
> +    <input (change)="toggleSwitched()" class="checkbox" type="checkbox" id="toggle" [(ngModel)]="isChecked">
אוקיי.

2022-04-14 09:51 UTC, merged